# Server
server.port=8002

# PostgreSQL (same DB server as user-service, different database)
spring.datasource.url=jdbc:postgresql://localhost:5432/quickbowl_orders
spring.datasource.username=postgres
spring.datasource.password=Ronaldo123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# App name
spring.application.name=order-service

# Actuator
management.endpoints.web.exposure.include=health,info

# Other services
app.restaurant-service.url=http://localhost:8001
app.user-service.url=http://localhost:3001

# Order settings
app.order.max-scheduled-days=7
app.order.penalty-percent=10
app.order.free-cancellation-minutes=5

spring.kafka.bootstrap-servers=${KAFKA_BROKER:kafka:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer