# Server
server.port=8002

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/quickbowl_orders}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Ronaldo123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# App name
spring.application.name=order-service

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BROKER:kafka:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Other services
app.restaurant-service.url=${RESTAURANT_SERVICE_URL:http://localhost:8001}
app.user-service.url=${USER_SERVICE_URL:http://localhost:3001}

# Order settings
app.order.max-scheduled-days=7
app.order.penalty-percent=10
app.order.free-cancellation-minutes=5

# Actuator + Prometheus
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

# OpenTelemetry
otel.service.name=${OTEL_SERVICE_NAME:order-service}
otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://otel-collector:4317}
otel.traces.exporter=otlp